// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codepilot
{
    internal sealed partial class Vsix
    {
        public const string Id = "Codepilot.a1a1bb91-5616-423d-bdf4-f2c296ae7bc6";
        public const string Name = "Codepilot";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
